name: sunny_essentials
version: 0.8.2+1
description: Just the basic widgets, with limited dependencies
repository: https://github.com/ericmartineau/sunny_essentials.git
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  logging: ^1.0.2
  provider: ^6.0.3
  octo_image: ^1.0.2
  recase: ^4.0.0
  timeago: ^3.2.2
  uri: ^1.0.0
  info_x: 
    git: 
      url: git@github.com:ericmartineau/info_x
      ref: trippi_app
  flutter_degen_annotations: 
    git: 
      url: git@github.com:ericmartineau/flutter_degen_annotations
      ref: trippi_app
  sunny_platform_widgets: 
    git: 
      url: git@github.com:SunnyApp/flutter_platform_widgets
      ref: trippi_app
  flutter_screen_scaling: 
    git: 
      url: git@github.com:SunnyApp/flutter_screen_scaling
      ref: trippi_app
  dartxx: 
    git: 
      url: git@github.com:ericmartineau/dartxx.git
      ref: trippi_app
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_degen: 
    git: 
      url: git@github.com:TrippiApp/flutter_degen
      ref: trippi_app
  flutter_test: 
    sdk: flutter
