name: sunny_essentials
description: Just the basic widgets, with limited dependencies
version: 0.4.4-nullsafety.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
#  badges: ^2.0.0-nullsafety.1
  cached_network_image: ^3.0.0-nullsafety
  equatable: ^2.0.0
#  expanding_cards: ^0.4.4
#  sunny_fluro: ^1.8.0-nullsafe.2
  flutter_degen: ^0.5.1-nullsafety.2
  flutter_platform_widgets: ^1.0.1-nullsafety.2
  flutter_screen_scaling: ^3.3.2+1
  logging: ^1.0.0
#  material_segmented_control: ^3.0.0-nullsafety.1
  dartxx: ^0.4.5-nullsafety.3
#  modal_bottom_sheet: ^2.0.0
#  permission_handler: ^6.1.1
  provider: ^5.0.0
#  responsive_builder: ^0.4.0-nullsafety.1
#  sunny_dart: ^0.8.2+2
#  sunny_sdk_core: ^2.0.0-nullsafe.16
  timeago: ^3.0.2
  uri: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
