name: sunny_essentials
version: 0.6.0+10
description: Just the basic widgets, with limited dependencies
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  cached_network_image: ^3.1.0
  dartxx: ^0.5.3+2
  equatable: ^2.0.3
  flutter_degen_annotations: ^1.4.0+1
  flutter_platform_widgets: ^1.9.5
  flutter_screen_scaling: ^3.3.2+3
  info_x: ^0.7.0+1
  logging: ^1.0.1
  provider: ^5.0.0
  recase: ^4.0.0
  timeago: ^3.1.0
  uri: ^1.0.0
  flutter: 
    sdk: flutter
dev_dependencies: 
  meta: ^1.7.0
  flutter_degen: ^0.7.0+2
  flutter_test: 
    sdk: flutter
dependency_overrides: 
  meta: ^1.7.0
