name: sunny_essentials
version: 0.6.0+2
description: Just the basic widgets, with limited dependencies
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  cached_network_image: ^3.0.0
  dartxx: ^0.5.0+2
  equatable: ^2.0.0
  flutter_degen: ^0.6.0+3
  flutter_platform_widgets: ^1.7.1
  flutter_screen_scaling: ^3.3.2+3
  info_x: ^0.6.0+1
  logging: ^1.0.1
  provider: ^5.0.0
  recase: ^4.0.0
  timeago: ^3.0.2
  uri: ^1.0.0
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
